"""Initial migration

Revision ID: a9593ce7b6f7
Revises: 
Create Date: 2025-11-27 14:39:02.009926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9593ce7b6f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuraciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuraciones_clave'), ['clave'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('google_scholar_id', sa.String(length=100), nullable=True),
    sa.Column('scopus_id', sa.String(length=100), nullable=True),
    sa.Column('orcid_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('docencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_curso', sa.String(length=200), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.Column('institucion', sa.String(length=200), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('horas', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('tamaño', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('organizador', sa.String(length=200), nullable=True),
    sa.Column('lugar', sa.String(length=200), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('autores', sa.Text(), nullable=True),
    sa.Column('revista', sa.String(length=300), nullable=True),
    sa.Column('volumen', sa.String(length=50), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('paginas', sa.String(length=50), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('indizada', sa.Boolean(), nullable=True),
    sa.Column('scopus_id', sa.String(length=100), nullable=True),
    sa.Column('pubmed_id', sa.String(length=100), nullable=True),
    sa.Column('scholar_id', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicaciones')
    op.drop_table('eventos')
    op.drop_table('documentos')
    op.drop_table('docencias')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('configuraciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuraciones_clave'))

    op.drop_table('configuraciones')
    # ### end Alembic commands ###
